# puts "Name is #{ ENV['NAME'] } "
KEY_CHAIN_NAME = ENV["MATCH_KEYCHAIN_NAME"]
KEY_CHAIN_PASSWORD = ENV["MATCH_KEYCHAIN_PASSWORD"]

default_platform(:ios)


platform :ios do
  # Creating temp keychain
  desc "Description of what the lane does"
  lane :create_temp_key_chain do
    puts "Creating temp keychain with name #{KEY_CHAIN_NAME}"
    create_keychain(
      name: KEY_CHAIN_NAME,
      password: KEY_CHAIN_PASSWORD,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
    )
  end

  # Creating temp keychain
  desc "Description of what the lane does"
  lane :delete_temp_key_chain do
    puts "Deleting temp keychain with name #{KEY_CHAIN_NAME}"
    delete_keychain(name: "#{KEY_CHAIN_NAME}")
  end
end
