# puts "Name is #{ ENV['NAME'] } "
KEY_CHAIN_NAME = ENV["MATCH_KEYCHAIN_NAME"]
KEY_CHAIN_PASSWORD = ENV["MATCH_KEYCHAIN_PASSWORD"]
USER_ID = ENV["USER_ID"]
MATCH_GIT_BASIC_AUTHORIZATION = ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    create_temp_key_chain
  end
  
  # Creating temp keychain
  desc "Running ... create_temp_key_chain"
  lane :create_temp_key_chain do
    puts "Creating temp keychain with name #{KEY_CHAIN_NAME}"
    create_keychain(
      name: KEY_CHAIN_NAME,
      password: KEY_CHAIN_PASSWORD,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
  end

  # Creating temp keychain
  desc "Running ... match_certificates"
  lane :match_and_sigin_certificates do
    puts "Running ... match_certificat #{KEY_CHAIN_NAME}"
    create_temp_key_chain
    match(
      keychain_name: KEY_CHAIN_NAME,
      keychain_password: KEY_CHAIN_PASSWORD,
      git_basic_authorization: MATCH_GIT_BASIC_AUTHORIZATION,
      readonly: true,
      verbose: true,
      skip_docs: true,
      verbose:true,
      git_basic_authorization:MATCH_GIT_BASIC_AUTHORIZATION
    )
    sync_code_signing(type: "adhoc", readonly: true)
  end


# Creating temp keychain
desc "Running ... archive_build"
lane :archive_build do
  puts "Running ... archive_build #{KEY_CHAIN_NAME}"
  match_and_sigin_certificates
  build_app(
    # app-store", "ad-hoc",  "enterprise", "development"]
      export_method:"ad-hoc",
      workspace: "ragnarok-app.xcworkspace",
      configuration: "Release",
      scheme: "QA",
      silent: true,
      clean: true,
      output_directory: "./builds",
      skip_codesigning: true,
      skip_build_archive: false,
      archive_path: "./builds",
      output_directory: "./builds",
      skip_package_ipa: false,
      export_team_id: 'BY9LWEKRD9'
  )
end

# delete_temp_key_chain
desc "Running ... delete_temp_key_chain"
lane :delete_temp_key_chain do
  puts "Deleting temp keychain with name #{KEY_CHAIN_NAME}"
  delete_keychain(name: "#{KEY_CHAIN_NAME}")
end

after_all do |lane, options|
  delete_temp_key_chain
end
end
