name: Creating Artifacts
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Creating folder Files.
        run:  mkdir $HOME/Files
      - name: Changing Directory 
        run: cd $HOME/Files
      - name: Printing current Directory     
        run: |
          echo 'Current folder'
          echo pwd