name: Artifacts Uploading
on: [push]
jobs:
  CreateArtifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Creating File artifacts
    - run: |
       mkdir Files
       cd Files
       touch Content.txt
       echo hello > ./Files/Content.txt
