name: Creating Artifacts
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Creating folder Files.
        run:  mkdir $HOME/Files
      - name: Changing Directory 
        run: cd $HOME/Files
      - name: Printing current Directory     
        run: |
          echo 'Current folder'
          touch Content.text
          echo 'Damodar' > Content.text
          cat Content.text
      - uses: actions/upload-artifact@v2
        with:
          name: Creating Artifacts 
          path: $HOME/Files/Content.text