name: Creating Artifacts
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Creating File into folder     
        run: |
          echo 'Creating Directory'
          mkdir -p Files
          cd Files
          touch Content.text
          echo 'Damodar' > Content.text
          cat Content.text
          open -a TextEdit Content.text
          ls
      - uses: actions/upload-artifact@v2
        with:
          name: Download-Artifacts 
          path: ./Files/Content.text