name: Creating Artifacts
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Creating Folder, file then writing on to it.
        run: |
          mkdir Files
          cd Files
          touch ./Files/Content.txt
          echo hello > ./Files/Content.txt
