name: Fastlane Create Keychain
on: [push]
jobs:
  CreateTempKeyChain:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: fastlane deploy
      run: fastlane archive_build
      env:
        MATCH_KEYCHAIN_NAME: 'Damodar_Key_Chain'
        MATCH_KEYCHAIN_PASSWORD: 'Damodar_Password_Chain'
        FASTLANE_APPLE_ID: 'damodar@backbase.com'
        MATCH_PASSWORD: '12345'
        APPLE_ISSUER_ID: '69a6de80-3fc1-47e3-e053-5b8c7c11a4d1'
        APPLE_KEY_ID: damodar@backbse.com
        APPLE_KEY_CONTENT: 'CUTA8L5N5R'
    - uses: actions/upload-artifact@v2
      with: 
        name: Download-Artifacts 
        path: ./builds


