name: Fastlane Create Keychain
on: [push]
jobs:
  CreateTempKeyChain:
    runs-on: macos-latest
    steps:   
    - name: fastlane deploy
      uses: maierj/fastlane-action@v1.4.0
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: cm9oaXRrdW1hcmJhY2tiYXNlOmdocF9FOFloSWxZNThJVFpScmJSM0E3eGdSQmJoTWdaVFYwendOSDU=
        MATCH_PASSWORD: Damodar_Password_Chain
        MATCH_KEYCHAIN_NAME: Damodar_Key_Chain
        MATCH_KEYCHAIN_PASSWORD: Damodar_Password_Chain
        lane: archive_build
        skip-tracking: false

    - uses: actions/upload-artifact@v2
      with: 
        name: Download-Artifacts 
        path: ./builds


