name: Fastlane Create Keychain
on: [push]
jobs:
  CreateTempKeyChain:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Creating Builds   
        run:  fastlane archive_build

      - uses: actions/upload-artifact@v2
        with:
          name: Download-Artifacts 
          path: ./builds


