  name: File Operaitions
  on: push
  jobs:
    descript:
      name: File Description
      runs-on: ubuntu-latest  
      steps:
        - uses: actions/checkout@v3
      
        - name: Set up secret file
          env:
            TOP_SECRET: ${{ secrets.TOP_SECRET }}
          run: |
            touch $HOME/secrets.txt
            echo $TOP_SECRET >> secrets.txt

        - name: Run tmate
          uses: mxschmitt/action-tmate@v2