name: Prining Secrets
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ONE: ${{secrets.PASS_PHRASE}}
        TWO: ${{secrets.SECRET_NAME}}
        THREE: ${{secrets.TOP_SECRET}}
      run: |
        echo "$ONE $TWO $THREE" |  sed 's/(\1\)/g'
