name: Prining Secrets
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ONE: ${{secrets.PASS_PHRASE}}
        TWO: ${{secrets.SECRET_NAME}}
        THREE: ${{secrets.TOP_SECRET}}
      run: |
        echo "$ONE $TWO $THREE" | sed 's/./& /g'
        sed -i 's/ $TWO /'  $HOME/text.txt > cat  $HOME/text.txt
        touch $HOME/text.txt
        echo "some data for the $THREE" >> $HOME/text.txt

    - name: Priniing Names
      run: cat $HOME/text.txt