name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GIT_SECRET: ${{secrets.TOP_SECRET}}
      run: | 
        touch $HOME/secret.txt
        echo "Greeting $GIT_SECRET" >>  $HOME/secret.txt
    - name: Set up secret file
      run: cat $HOME/secret.txt

