  name: Env vars
  on: push
  jobs:
    debug:
      name: Print Github Secret
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Set up secret file
          env:
            TOP_SECRET: ${{ secrets.TOP_SECRET }}
          run: |
            touch $HOME/SECRET_NAME.text 
            echo $TOP_SECRET >> SECRET_NAME.text
        - name: Print file content 
          run: cat $HOME/SECRET_NAME.text
    