name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        TOP_SECRET: ${{ secrets.TOP_SECRET }}
      run: |
        echo env.TOP_SECRET  >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
