name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ONE: ${{secrets.PASS_PHRASE}}
        TWO: ${{secrets.SECRET_NAME}}
        THREE: ${{secrets.TOP_SECRET}}

      run: echo $ONE $TWO $THREE | sed 's/./& /g'

        # touch $HOME/secret.txt
        # echo "Greeting  $ONE $TWO $THREE" >>  secret.txt
   
    - name: Set up secret file
      run: |
        echo "$env.TWO $envONE $env.THREE" >> secret.txt
        cat $HOME/secret.txt

