name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      run: echo ${{secrets.GIT_SECRET }} | sed 's/./& /g'


