name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Printing TOP_SECRET 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ONE: ${{secrets.PASS_PHRASE}}
        TWO: ${{secrets.SECRET_NAME}}
        THREE: ${{secrets.TOP_SECRET}}
      run: echo $ONE $TWO $THREE | sed 's/./& /g'

    - name: Set up secret file
      run: |
        touch $HOME/text.txt
        echo $env.TWO >> $HOME/text.txt
        cat $HOME/text.txt

